#!/usr/bin/env python3
"""
Azure ML Environment Setup - Manual Configuration
Run this after you've manually set up your Azure environment.
"""

import os
import subprocess
import json
from pathlib import Path


def run_command(cmd, capture_output=True):
    """Run a shell command and return the result"""
    try:
        result = subprocess.run(cmd, shell=True, capture_output=capture_output, text=True)
        return result.returncode == 0, result.stdout.strip(), result.stderr.strip()
    except Exception as e:
        return False, "", str(e)


def check_azure_login():
    """Check if user is logged in to Azure"""
    success, _, _ = run_command("az account show")
    return success


def get_current_subscription():
    """Get current subscription info"""
    success, stdout, _ = run_command("az account show --output json")
    if success:
        try:
            return json.loads(stdout)
        except json.JSONDecodeError:
            pass
    return None


def create_resource_group(name, location="westus2"):
    """Create a resource group"""
    print(f"📦 Creating resource group '{name}' in {location}...")
    success, _, stderr = run_command(f"az group create --name {name} --location {location}")
    if success:
        print(f"✅ Created resource group: {name}")
        return True
    else:
        print(f"❌ Failed to create resource group: {stderr}")
        return False


def create_ml_workspace(name, resource_group, location="westus2"):
    """Create an Azure ML workspace"""
    print(f"🧪 Creating ML workspace '{name}'...")
    success, _, stderr = run_command(
        f"az ml workspace create --name {name} --resource-group {resource_group} --location {location}"
    )
    if success:
        print(f"✅ Created ML workspace: {name}")
        return True
    else:
        print(f"❌ Failed to create workspace: {stderr}")
        return False


def create_compute_cluster(resource_group, workspace):
    """Create a CPU compute cluster"""
    print("🖥️ Creating CPU compute cluster...")
    success, _, stderr = run_command(
        f"az ml compute create --name cpu-cluster --type AmlCompute "
        f"--size Standard_DS3_v2 --min-instances 0 --max-instances 4 "
        f"--resource-group {resource_group} --workspace-name {workspace}"
    )
    if success:
        print("✅ Created compute cluster: cpu-cluster")
        return True
    else:
        print(f"❌ Failed to create compute cluster: {stderr}")
        return False


def save_environment_file(subscription_id, resource_group, workspace):
    """Save environment variables"""
    env_content = f"""# Azure ML Environment Configuration
# Generated by setup_azure_ml_manual.py

AZURE_SUBSCRIPTION_ID={subscription_id}
AZURE_RESOURCE_GROUP={resource_group}
AZURE_ML_WORKSPACE_NAME={workspace}
"""

    env_file = Path(".env")
    with open(env_file, 'w') as f:
        f.write(env_content)

    print(f"✅ Environment configuration saved to {env_file}")
    print("   Load these variables with: source .env")


def main():
    """Main setup function"""
    print("🚀 MILLENNIALAI AZURE ML MANUAL SETUP")
    print("=" * 45)

    # Check if logged in
    if not check_azure_login():
        print("❌ Not logged in to Azure. Please run:")
        print("   az login --use-device-code")
        print("   Then visit https://microsoft.com/devicelogin with the code")
        return

    # Get current subscription
    subscription = get_current_subscription()
    if not subscription:
        print("❌ Could not get subscription info")
        return

    print(f"📋 Current subscription: {subscription.get('name', 'Unknown')} ({subscription['id']})")

    # Get resource group name
    rg_name = input("Enter resource group name (or press Enter for 'millennialai-rg'): ").strip()
    if not rg_name:
        rg_name = "millennialai-rg"

    # Get workspace name
    ws_name = input("Enter ML workspace name (or press Enter for 'millennialai-ws'): ").strip()
    if not ws_name:
        ws_name = "millennialai-ws"

    # Get location
    location = input("Enter Azure region (or press Enter for 'westus2'): ").strip()
    if not location:
        location = "westus2"

    # Create resources
    if not create_resource_group(rg_name, location):
        return

    if not create_ml_workspace(ws_name, rg_name, location):
        return

    if not create_compute_cluster(rg_name, ws_name):
        print("⚠️ Compute cluster creation failed, but you can create it manually later")

    # Save configuration
    save_environment_file(subscription['id'], rg_name, ws_name)

    print("\n🎉 Azure ML environment setup complete!")
    print("\n📋 Summary:")
    print(f"   Subscription: {subscription.get('name', 'Unknown')} ({subscription['id']})")
    print(f"   Resource Group: {rg_name}")
    print(f"   ML Workspace: {ws_name}")
    print("   Compute: cpu-cluster (CPU compute for testing)")

    print("\n🧪 Ready to run tests:")
    print("   source .env")
    print("   python submit_azure_test.py")

    print("\n📖 For more information, see AZURE_ML_SETUP.md")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
    except Exception as e:
        print(f"\n❌ Setup failed with error: {e}")