"""
Constants and configuration values for MillennialAi

This module contains all hardcoded values that should be configurable,
replacing magic numbers throughout the codebase.
"""

# Model Architecture Constants
DEFAULT_HIDDEN_SIZE = 768
DEFAULT_NUM_HEADS = 12
DEFAULT_FF_HIDDEN_SIZE = 3072  # 4x hidden_size
DEFAULT_NUM_LAYERS = 12
DEFAULT_VOCAB_SIZE = 50257  # GPT-2 vocab size

# TRM Architecture Constants
DEFAULT_TRM_HIDDEN_SIZE = 512
DEFAULT_TRM_NUM_HEADS = 8
DEFAULT_TRM_FF_HIDDEN_SIZE = 2048  # 4x trm_hidden_size
DEFAULT_TRM_NUM_LAYERS = 2
DEFAULT_NUM_RECURSION_STEPS = 3

# Training Constants
DEFAULT_DROPOUT = 0.1
DEFAULT_LAYER_NORM_EPS = 1e-5
DEFAULT_RECURSION_DROPOUT = 0.05
DEFAULT_INJECTION_STRENGTH = 1.0

# GUI Constants
DEFAULT_WINDOW_WIDTH = 1400
DEFAULT_WINDOW_HEIGHT = 900
DEFAULT_WINDOW_X = 100
DEFAULT_WINDOW_Y = 100
DEFAULT_UPDATE_INTERVAL_MS = 1000  # 1 second

# UI Range Constants
MIN_LAYERS = 1
MAX_LAYERS = 100
DEFAULT_DEPTH_VALUE = 10
MIN_SAMPLES = 1000
MAX_SAMPLES = 1000000
DEFAULT_SAMPLES_VALUE = 10000

# Model Generation Constants
DEFAULT_MAX_LENGTH = 100
COMPLEXITY_DIVISOR = 100.0
COMPLEXITY_MULTIPLIER = 10

# Test Constants
TEST_SEQUENCE_LENGTH = 10
TEST_BATCH_SIZE = 1
TEST_VARIANCE_LOW = 0.1
TEST_VARIANCE_MEDIUM = 1.0
TEST_VARIANCE_HIGH = 3.0

# Complexity Heuristics
COMPLEXITY_DIVISOR = 100.0
COMPLEXITY_MULTIPLIER = 10
MAX_COMPLEXITY_STEPS = 50

# File Paths and URLs
DEFAULT_MODEL_CACHE_DIR = "~/.cache/huggingface"
DEFAULT_CONFIG_FILE = "config.json"
DEFAULT_WEIGHTS_FILE = "pytorch_model.bin"

# Azure ML Constants
DEFAULT_COMPUTE_CLUSTER = "cpu-cluster"
DEFAULT_ENVIRONMENT_NAME = "millennialai-training"
DEFAULT_EXPERIMENT_NAME = "millennialai-experiment"

# Performance Constants
DEFAULT_GRADIENT_ACCUMULATION_STEPS = 1
DEFAULT_MAX_GRAD_NORM = 1.0
DEFAULT_WARMUP_RATIO = 0.1

# Memory Constants
DEFAULT_MEMORY_SIZE = 256
DEFAULT_ATTENTION_CACHE_SIZE = 1024